### PR TITLE
【課題解決Wiki】SphereColliderをクリックしても反応しない問題

### PR DESCRIPTION
**Pull request by ra9g16**
### **PR Type**
Documentation

___

### **Description**
- 新しいFAQページを追加し、旧MyVketでのプロフィール画像エラーの解決方法を英語と日本語で記載。
- SphereColliderクリック反応問題に関するFAQを英語と日本語で追加。
- 変更ログを更新し、新しいFAQページの追加を記録。
- mkdocsのナビゲーションを更新し、新しいFAQエントリを含める。

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>ProfileImage.en.md</strong><dd><code>Add FAQ for Profile Image Error on Old MyVket</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/FAQ/ProfileImage.en.md

<li>Added a new FAQ page for resolving profile image errors on old MyVket.<br> <li> Described the issue, environment, and steps taken to resolve it.<br> <li> Provided a conclusion and recommendation for users.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-ee41d910b88bbc2b3a1cfd1f1a5e1736baf46c0e4aef29247b2fbb511140cc32">+26/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>ProfileImage.ja.md</strong><dd><code>旧MyVketでのプロフィール画像エラーに関するFAQ追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/FAQ/ProfileImage.ja.md

<li>Added a new FAQ page in Japanese for profile image errors on old <br>MyVket.<br> <li> Included issue description, environment details, and resolution steps.<br> <li> Offered a conclusion and advice for users.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-2474bf5fad70e0010046c0b71bc7a15e28bcc91f87c923c6fe459358770ca9ae">+28/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>SphereCollider.en.md</strong><dd><code>Add FAQ for SphereCollider Click Response Issue</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/FAQ/SphereCollider.en.md

<li>Added a new FAQ page for SphereCollider click response issues.<br> <li> Explained the issue, cause, and solution.<br> <li> Included pitfalls and additional information.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-afb2974e394e7cb6a949cea44783ea0cfd0f05ef4f56de91835c5f51c7549697">+34/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>SphereCollider.ja.md</strong><dd><code>SphereColliderクリック反応問題に関するFAQ追加</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/FAQ/SphereCollider.ja.md

<li>Added a new FAQ page in Japanese for SphereCollider click issues.<br> <li> Detailed the issue, cause, and solution.<br> <li> Provided pitfalls and supplementary information.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-8244623d03489d34eb1b3e2c543732250068faa1a23fb6ee8bdbb71c0667f5db">+36/-0</a>&nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.en.md</strong><dd><code>Update Changelog for New FAQ Pages</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/changelog/changelog-14.2.en.md

<li>Updated changelog to include new FAQ pages.<br> <li> Documented the addition of the Profile Image Error solution.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-2f3baf40cb41ed78decf8d39000daef3a13e7b63f50de72c9d8a685e1356d6bb">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>

<tr>
  <td>
    <details>
      <summary><strong>changelog-14.2.ja.md</strong><dd><code>新しいFAQページのための変更ログ更新</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

docs/changelog/changelog-14.2.ja.md

<li>Updated Japanese changelog to reflect new FAQ pages.<br> <li> Included entry for Profile Image Error solution.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-a8f7442620adccd75c20db969e01eb0df04d1ae71c0bdda20f51ce3726dd1a5b">+9/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr><tr><td><strong>Configuration changes</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>mkdocs.yml</strong><dd><code>Update mkdocs Navigation for New FAQ Entries</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

mkdocs.yml

<li>Added new FAQ entries to the documentation navigation.<br> <li> Included Profile Image Error solution in the FAQ section.<br>

</details>

  </td>
  <td><a href="https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/files#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2">+5/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by Kondo-Totori** [comment]
※日本語ドキュメントの身を確認しています。
SphereCollider.ja
GameObjectのスケール値が小さい → GameObjectのスケール値がX、Y、Zで同値でない

SphereCollider_3.jpg
プロジェクト名に含まれる「aschild」は具体的な企業名を指すため、隠してください。

**Review by Negi-T — APPROVED** [review]
LGTM!

**Comment by ra9g16** [comment]
> ※日本語ドキュメントの身を確認しています。 SphereCollider.ja GameObjectのスケール値が小さい → GameObjectのスケール値がX、Y、Zで同値でない
> 
> SphereCollider_3.jpg プロジェクト名に含まれる「aschild」は具体的な企業名を指すため、隠してください。

https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/commits/ff729e12e65cbd9b898f6057385a700c44aaad33
https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/commits/a6abf2c4673c271105c4c1332377d5c77fd81066
https://github.com/VRHIKKY/VketCloudSDK_Documents/pull/553/commits/a305ee31fec56bf93cf697d87c418bb29bd9cb7e

**Review by Kondo-Totori — APPROVED** [review]
LGTM!

**Review by Negi-T — APPROVED** [review]
LGTM!

**Pull request merged**
